// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf3zdml-VqwHp8z74wqIPQZpm3ZGjpvz8',
    appId: '1:627606503594:web:35067844b0e26fc20210d3',
    messagingSenderId: '627606503594',
    projectId: 'fire-chat-6b60b',
    authDomain: 'fire-chat-6b60b.firebaseapp.com',
    storageBucket: 'fire-chat-6b60b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5xxHgCJ0fqNuJA-QuTnvQAudkKOnAzG8',
    appId: '1:627606503594:android:ab9d8a04d0ba33a60210d3',
    messagingSenderId: '627606503594',
    projectId: 'fire-chat-6b60b',
    storageBucket: 'fire-chat-6b60b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWxtZUi43lV95AVhWJeEaZuBEqFGJXU8',
    appId: '1:627606503594:ios:0c916bcb296e19810210d3',
    messagingSenderId: '627606503594',
    projectId: 'fire-chat-6b60b',
    storageBucket: 'fire-chat-6b60b.appspot.com',
    iosBundleId: 'com.example.fireChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByWxtZUi43lV95AVhWJeEaZuBEqFGJXU8',
    appId: '1:627606503594:ios:1fa1ccf4580f332e0210d3',
    messagingSenderId: '627606503594',
    projectId: 'fire-chat-6b60b',
    storageBucket: 'fire-chat-6b60b.appspot.com',
    iosBundleId: 'com.example.fireChat.RunnerTests',
  );
}
